site_name: GitPlus

pages:
- Home: 'index.md'
- 'Build Properties': 'build-properties.md'
- 'Change Log Configuration':'change-log-configuration.md'
- 'GitPlus Configuration':'gitplus-configuration.md'
- 'Change Log': 'changelog.md'
- Licence: 'license.md'

theme: readthedocs



